### PR TITLE
[3.4] Improve project description

### PR DESCRIPTION
**Pull request by TavoNiievez**

### CODE REVIEW

**Comment by Naktibalda** [comment]
Why could anyone want to create a new project based on this repository?

**Comment by TavoNiievez** [comment]
To reproduce a bug and share it for investigation.
To verify the operation of a method in a minimal installation of the framework.
To analyze configuration details that may be causing problems in the personal project.

`composer create-project` is just a shortcut for `git clone` and `composer install`. Besides that, it allows to include scripts and to be able to automate the steps that were previously manual, such as configuring the database.

The purpose of the project **is not** to serve as a template.

**Comment by Naktibalda** [comment]
Is it possible to raise a pull request to this repository from project created using `composer create-project`?

**Comment by TavoNiievez** [comment]
also not possible with  `git clone https://github.com/Codeception/symfony-module-tests.git`

**Comment by TavoNiievez** [comment]
If replacing the long way with the short one does not convince you (I repeat, the behavior is exactly the same), I can modify the PRs so that the long version remains as an option. I can also include a description of what is the *expected* use of the project.

I just need you to tell me what changes you would like.

**Comment by TavoNiievez** [comment]
Including a link to the contribution guides could also be helpful.

**Comment by Naktibalda** [comment]
Then these instructions aren't (and weren't) fit for purpose "to reproduce a bug and share it for investigation".

I think that it would be the best to delete installation instructions and replace them with link to your contribution guide https://github.com/Codeception/module-symfony/blob/master/CONTRIBUTING.md

**Comment by TavoNiievez** [comment]
well, at some point you had to install the project 😆 .

OK, I'll make the changes at the end of the day.

Thanks for the feedback

**Comment by TavoNiievez** [comment]
@Naktibalda I made the changes. Is it better this way?

**Comment by ThomasLandauer** [comment]
I think you shouldn't remove the installation instructions, since they're referenced at https://github.com/Codeception/module-symfony/blob/master/CONTRIBUTING.md

> Go to Codeception/symfony-module-tests and fork the project. Then follow the installation instructions.

**Comment by TavoNiievez** [comment]
Just to be clear what the contribution guides say is to 'follow the instructions', if I remove the above then they would have to be added to the contribution guides themselves.

**Comment by TavoNiievez** [comment]
What **Naktibalda** suggests is that they be added to the contribution guides.

Since the exact command, you must run if you want to contribute involves cloning your fork, and not cloning the original repository.

**Comment by TavoNiievez** [comment]
@ThomasLandauer Can you please include the 3 commands that I remove here in the contribution guides?
```
1. Clone your fork locally
2. Install Composer dependencies
3. Update database schema and load Doctrine fixtures
```

It can be in the PR that you have open.

**Comment by TavoNiievez** [comment]
Just for the record i proposed this because installing [phalcon/demo](https://github.com/Codeception/phalcon-demo) with composer is already possible and even the test project readme explains both

**Pull request merged**
